// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: meta_service.proto

package meta_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryStatus int32

const (
	// Metadata is registered, but the entity data has not been uploaded.
	EntryStatus_Registered EntryStatus = 0
	// The metadata is registered and some entity data is being stored.
	EntryStatus_Storing EntryStatus = 1
	// The storage entity is fully stored and available.
	EntryStatus_Available EntryStatus = 2
	// Storage entity has been deleted and will be purged periodically.
	EntryStatus_Deleted EntryStatus = 3
)

// Enum value maps for EntryStatus.
var (
	EntryStatus_name = map[int32]string{
		0: "Registered",
		1: "Storing",
		2: "Available",
		3: "Deleted",
	}
	EntryStatus_value = map[string]int32{
		"Registered": 0,
		"Storing":    1,
		"Available":  2,
		"Deleted":    3,
	}
)

func (x EntryStatus) Enum() *EntryStatus {
	p := new(EntryStatus)
	*p = x
	return p
}

func (x EntryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_meta_service_proto_enumTypes[0].Descriptor()
}

func (EntryStatus) Type() protoreflect.EnumType {
	return &file_meta_service_proto_enumTypes[0]
}

func (x EntryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryStatus.Descriptor instead.
func (EntryStatus) EnumDescriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{0}
}

type ObjectMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueKey string      `protobuf:"bytes,1,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"`         // the unique key of object
	Status    EntryStatus `protobuf:"varint,2,opt,name=status,proto3,enum=meta_service.EntryStatus" json:"status,omitempty"` // the status of object
	Size      int64       `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`                                   // byte unit size of the object
	ChunkList []string    `protobuf:"bytes,4,rep,name=chunk_list,json=chunkList,proto3" json:"chunk_list,omitempty"`         // chunk list of the object to which it belongs
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMeta) GetUniqueKey() string {
	if x != nil {
		return x.UniqueKey
	}
	return ""
}

func (x *ObjectMeta) GetStatus() EntryStatus {
	if x != nil {
		return x.Status
	}
	return EntryStatus_Registered
}

func (x *ObjectMeta) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ObjectMeta) GetChunkList() []string {
	if x != nil {
		return x.ChunkList
	}
	return nil
}

type ChunkMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueKey  string      `protobuf:"bytes,1,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"`         // the unique key of chunk
	Status     EntryStatus `protobuf:"varint,2,opt,name=status,proto3,enum=meta_service.EntryStatus" json:"status,omitempty"` // the status of chunk
	Parent     string      `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`                                // the object unique key to which the chunk belongs
	Index      int64       `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`                                 // chunk's order in the whole object
	StoreGroup int64       `protobuf:"varint,5,opt,name=store_group,json=storeGroup,proto3" json:"store_group,omitempty"`     // block storage Raft group where chunk are stored
}

func (x *ChunkMeta) Reset() {
	*x = ChunkMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChunkMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkMeta) ProtoMessage() {}

func (x *ChunkMeta) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkMeta.ProtoReflect.Descriptor instead.
func (*ChunkMeta) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkMeta) GetUniqueKey() string {
	if x != nil {
		return x.UniqueKey
	}
	return ""
}

func (x *ChunkMeta) GetStatus() EntryStatus {
	if x != nil {
		return x.Status
	}
	return EntryStatus_Registered
}

func (x *ChunkMeta) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ChunkMeta) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChunkMeta) GetStoreGroup() int64 {
	if x != nil {
		return x.StoreGroup
	}
	return 0
}

type QueryObjectMetaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueKey string `protobuf:"bytes,1,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"`
}

func (x *QueryObjectMetaReq) Reset() {
	*x = QueryObjectMetaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryObjectMetaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryObjectMetaReq) ProtoMessage() {}

func (x *QueryObjectMetaReq) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryObjectMetaReq.ProtoReflect.Descriptor instead.
func (*QueryObjectMetaReq) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{2}
}

func (x *QueryObjectMetaReq) GetUniqueKey() string {
	if x != nil {
		return x.UniqueKey
	}
	return ""
}

type QueryObjectMetaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *ObjectMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *QueryObjectMetaResp) Reset() {
	*x = QueryObjectMetaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryObjectMetaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryObjectMetaResp) ProtoMessage() {}

func (x *QueryObjectMetaResp) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryObjectMetaResp.ProtoReflect.Descriptor instead.
func (*QueryObjectMetaResp) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{3}
}

func (x *QueryObjectMetaResp) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type QueryObjectKeysReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix   string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Page     int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *QueryObjectKeysReq) Reset() {
	*x = QueryObjectKeysReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryObjectKeysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryObjectKeysReq) ProtoMessage() {}

func (x *QueryObjectKeysReq) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryObjectKeysReq.ProtoReflect.Descriptor instead.
func (*QueryObjectKeysReq) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{4}
}

func (x *QueryObjectKeysReq) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *QueryObjectKeysReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryObjectKeysReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type QueryObjectKeysResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueKeys []string `protobuf:"bytes,1,rep,name=unique_keys,json=uniqueKeys,proto3" json:"unique_keys,omitempty"`
	Total      int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *QueryObjectKeysResp) Reset() {
	*x = QueryObjectKeysResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryObjectKeysResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryObjectKeysResp) ProtoMessage() {}

func (x *QueryObjectKeysResp) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryObjectKeysResp.ProtoReflect.Descriptor instead.
func (*QueryObjectKeysResp) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{5}
}

func (x *QueryObjectKeysResp) GetUniqueKeys() []string {
	if x != nil {
		return x.UniqueKeys
	}
	return nil
}

func (x *QueryObjectKeysResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateObjectStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueKey string      `protobuf:"bytes,1,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"`
	Status    EntryStatus `protobuf:"varint,2,opt,name=status,proto3,enum=meta_service.EntryStatus" json:"status,omitempty"`
}

func (x *UpdateObjectStatusReq) Reset() {
	*x = UpdateObjectStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateObjectStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObjectStatusReq) ProtoMessage() {}

func (x *UpdateObjectStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObjectStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateObjectStatusReq) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateObjectStatusReq) GetUniqueKey() string {
	if x != nil {
		return x.UniqueKey
	}
	return ""
}

func (x *UpdateObjectStatusReq) GetStatus() EntryStatus {
	if x != nil {
		return x.Status
	}
	return EntryStatus_Registered
}

type UpdateObjectStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateObjectStatusResp) Reset() {
	*x = UpdateObjectStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateObjectStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObjectStatusResp) ProtoMessage() {}

func (x *UpdateObjectStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObjectStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateObjectStatusResp) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{7}
}

type QueryChunkMetaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueKeys []string `protobuf:"bytes,1,rep,name=unique_keys,json=uniqueKeys,proto3" json:"unique_keys,omitempty"`
}

func (x *QueryChunkMetaReq) Reset() {
	*x = QueryChunkMetaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryChunkMetaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChunkMetaReq) ProtoMessage() {}

func (x *QueryChunkMetaReq) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChunkMetaReq.ProtoReflect.Descriptor instead.
func (*QueryChunkMetaReq) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{8}
}

func (x *QueryChunkMetaReq) GetUniqueKeys() []string {
	if x != nil {
		return x.UniqueKeys
	}
	return nil
}

type QueryChunkMetaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result map[string]*ChunkMeta `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *QueryChunkMetaResp) Reset() {
	*x = QueryChunkMetaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryChunkMetaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChunkMetaResp) ProtoMessage() {}

func (x *QueryChunkMetaResp) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChunkMetaResp.ProtoReflect.Descriptor instead.
func (*QueryChunkMetaResp) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{9}
}

func (x *QueryChunkMetaResp) GetResult() map[string]*ChunkMeta {
	if x != nil {
		return x.Result
	}
	return nil
}

type UpdateChunkStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueKeys []string    `protobuf:"bytes,1,rep,name=unique_keys,json=uniqueKeys,proto3" json:"unique_keys,omitempty"`
	Status     EntryStatus `protobuf:"varint,2,opt,name=status,proto3,enum=meta_service.EntryStatus" json:"status,omitempty"`
}

func (x *UpdateChunkStatusReq) Reset() {
	*x = UpdateChunkStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateChunkStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChunkStatusReq) ProtoMessage() {}

func (x *UpdateChunkStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChunkStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateChunkStatusReq) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateChunkStatusReq) GetUniqueKeys() []string {
	if x != nil {
		return x.UniqueKeys
	}
	return nil
}

func (x *UpdateChunkStatusReq) GetStatus() EntryStatus {
	if x != nil {
		return x.Status
	}
	return EntryStatus_Registered
}

type UpdateChunkStatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateChunkStatusResp) Reset() {
	*x = UpdateChunkStatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateChunkStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChunkStatusResp) ProtoMessage() {}

func (x *UpdateChunkStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChunkStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateChunkStatusResp) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{11}
}

// Before uploading a new object, it need to register and initialize the
// metadata, after which a unique key and a constructed route table are returned.
type RegisterObjectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size     int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	HashList []string `protobuf:"bytes,3,rep,name=hash_list,json=hashList,proto3" json:"hash_list,omitempty"`
}

func (x *RegisterObjectReq) Reset() {
	*x = RegisterObjectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterObjectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterObjectReq) ProtoMessage() {}

func (x *RegisterObjectReq) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterObjectReq.ProtoReflect.Descriptor instead.
func (*RegisterObjectReq) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterObjectReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterObjectReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RegisterObjectReq) GetHashList() []string {
	if x != nil {
		return x.HashList
	}
	return nil
}

type RegisterObjectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *ObjectMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *RegisterObjectResp) Reset() {
	*x = RegisterObjectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterObjectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterObjectResp) ProtoMessage() {}

func (x *RegisterObjectResp) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterObjectResp.ProtoReflect.Descriptor instead.
func (*RegisterObjectResp) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterObjectResp) GetMeta() *ObjectMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type QueryStorageAddressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StoreGroup int64 `protobuf:"varint,1,opt,name=store_group,json=storeGroup,proto3" json:"store_group,omitempty"`
	FromMaster bool  `protobuf:"varint,2,opt,name=from_master,json=fromMaster,proto3" json:"from_master,omitempty"`
}

func (x *QueryStorageAddressReq) Reset() {
	*x = QueryStorageAddressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStorageAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStorageAddressReq) ProtoMessage() {}

func (x *QueryStorageAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStorageAddressReq.ProtoReflect.Descriptor instead.
func (*QueryStorageAddressReq) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{14}
}

func (x *QueryStorageAddressReq) GetStoreGroup() int64 {
	if x != nil {
		return x.StoreGroup
	}
	return 0
}

func (x *QueryStorageAddressReq) GetFromMaster() bool {
	if x != nil {
		return x.FromMaster
	}
	return false
}

type QueryStorageAddressResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddressList []string `protobuf:"bytes,1,rep,name=address_list,json=addressList,proto3" json:"address_list,omitempty"`
}

func (x *QueryStorageAddressResp) Reset() {
	*x = QueryStorageAddressResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryStorageAddressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStorageAddressResp) ProtoMessage() {}

func (x *QueryStorageAddressResp) ProtoReflect() protoreflect.Message {
	mi := &file_meta_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStorageAddressResp.ProtoReflect.Descriptor instead.
func (*QueryStorageAddressResp) Descriptor() ([]byte, []int) {
	return file_meta_service_proto_rawDescGZIP(), []int{15}
}

func (x *QueryStorageAddressResp) GetAddressList() []string {
	if x != nil {
		return x.AddressList
	}
	return nil
}

var File_meta_service_proto protoreflect.FileDescriptor

var file_meta_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x22, 0x91, 0x01, 0x0a, 0x0a, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74,
	0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4b, 0x65, 0x79,
	0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x19, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x75, 0x6e, 0x6b,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xac, 0x01, 0x0a, 0x09, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x33, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x75,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x43, 0x0a, 0x13, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2c, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22,
	0x5d, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65,
	0x79, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x4c,
	0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x69, 0x0a, 0x15,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x4b, 0x65, 0x79, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x34, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x4d,
	0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x22, 0xae, 0x01, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x44,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x1a, 0x52, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x6a, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4b, 0x65, 0x79,
	0x73, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x19, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x58, 0x0a,
	0x11, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61,
	0x73, 0x68, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x61, 0x73, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a,
	0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65,
	0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x5a, 0x0a, 0x16, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x66, 0x72, 0x6f,
	0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x3c, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x2a, 0x46, 0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x65, 0x64, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x69, 0x6e, 0x67, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x02,
	0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x03, 0x32, 0x98, 0x05,
	0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a,
	0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x12, 0x20, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x1a, 0x21, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x20, 0x2e, 0x6d, 0x65, 0x74,
	0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x61, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1f, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x11, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x22, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1f, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x20,
	0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x64, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x24, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x25, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x6d, 0x65,
	0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_meta_service_proto_rawDescOnce sync.Once
	file_meta_service_proto_rawDescData = file_meta_service_proto_rawDesc
)

func file_meta_service_proto_rawDescGZIP() []byte {
	file_meta_service_proto_rawDescOnce.Do(func() {
		file_meta_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_service_proto_rawDescData)
	})
	return file_meta_service_proto_rawDescData
}

var file_meta_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meta_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_meta_service_proto_goTypes = []interface{}{
	(EntryStatus)(0),                // 0: meta_service.EntryStatus
	(*ObjectMeta)(nil),              // 1: meta_service.ObjectMeta
	(*ChunkMeta)(nil),               // 2: meta_service.ChunkMeta
	(*QueryObjectMetaReq)(nil),      // 3: meta_service.QueryObjectMetaReq
	(*QueryObjectMetaResp)(nil),     // 4: meta_service.QueryObjectMetaResp
	(*QueryObjectKeysReq)(nil),      // 5: meta_service.QueryObjectKeysReq
	(*QueryObjectKeysResp)(nil),     // 6: meta_service.QueryObjectKeysResp
	(*UpdateObjectStatusReq)(nil),   // 7: meta_service.UpdateObjectStatusReq
	(*UpdateObjectStatusResp)(nil),  // 8: meta_service.UpdateObjectStatusResp
	(*QueryChunkMetaReq)(nil),       // 9: meta_service.QueryChunkMetaReq
	(*QueryChunkMetaResp)(nil),      // 10: meta_service.QueryChunkMetaResp
	(*UpdateChunkStatusReq)(nil),    // 11: meta_service.UpdateChunkStatusReq
	(*UpdateChunkStatusResp)(nil),   // 12: meta_service.UpdateChunkStatusResp
	(*RegisterObjectReq)(nil),       // 13: meta_service.RegisterObjectReq
	(*RegisterObjectResp)(nil),      // 14: meta_service.RegisterObjectResp
	(*QueryStorageAddressReq)(nil),  // 15: meta_service.QueryStorageAddressReq
	(*QueryStorageAddressResp)(nil), // 16: meta_service.QueryStorageAddressResp
	nil,                             // 17: meta_service.QueryChunkMetaResp.ResultEntry
}
var file_meta_service_proto_depIdxs = []int32{
	0,  // 0: meta_service.ObjectMeta.status:type_name -> meta_service.EntryStatus
	0,  // 1: meta_service.ChunkMeta.status:type_name -> meta_service.EntryStatus
	1,  // 2: meta_service.QueryObjectMetaResp.meta:type_name -> meta_service.ObjectMeta
	0,  // 3: meta_service.UpdateObjectStatusReq.status:type_name -> meta_service.EntryStatus
	17, // 4: meta_service.QueryChunkMetaResp.result:type_name -> meta_service.QueryChunkMetaResp.ResultEntry
	0,  // 5: meta_service.UpdateChunkStatusReq.status:type_name -> meta_service.EntryStatus
	1,  // 6: meta_service.RegisterObjectResp.meta:type_name -> meta_service.ObjectMeta
	2,  // 7: meta_service.QueryChunkMetaResp.ResultEntry.value:type_name -> meta_service.ChunkMeta
	3,  // 8: meta_service.MetaService.QueryObjectMeta:input_type -> meta_service.QueryObjectMetaReq
	5,  // 9: meta_service.MetaService.QueryObjectKeys:input_type -> meta_service.QueryObjectKeysReq
	7,  // 10: meta_service.MetaService.UpdateObjectStatus:input_type -> meta_service.UpdateObjectStatusReq
	9,  // 11: meta_service.MetaService.QueryChunkMeta:input_type -> meta_service.QueryChunkMetaReq
	11, // 12: meta_service.MetaService.UpdateChunkStatus:input_type -> meta_service.UpdateChunkStatusReq
	13, // 13: meta_service.MetaService.RegisterObject:input_type -> meta_service.RegisterObjectReq
	15, // 14: meta_service.MetaService.QueryStorageAddress:input_type -> meta_service.QueryStorageAddressReq
	4,  // 15: meta_service.MetaService.QueryObjectMeta:output_type -> meta_service.QueryObjectMetaResp
	6,  // 16: meta_service.MetaService.QueryObjectKeys:output_type -> meta_service.QueryObjectKeysResp
	8,  // 17: meta_service.MetaService.UpdateObjectStatus:output_type -> meta_service.UpdateObjectStatusResp
	10, // 18: meta_service.MetaService.QueryChunkMeta:output_type -> meta_service.QueryChunkMetaResp
	12, // 19: meta_service.MetaService.UpdateChunkStatus:output_type -> meta_service.UpdateChunkStatusResp
	14, // 20: meta_service.MetaService.RegisterObject:output_type -> meta_service.RegisterObjectResp
	16, // 21: meta_service.MetaService.QueryStorageAddress:output_type -> meta_service.QueryStorageAddressResp
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_meta_service_proto_init() }
func file_meta_service_proto_init() {
	if File_meta_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meta_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChunkMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryObjectMetaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryObjectMetaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryObjectKeysReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryObjectKeysResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateObjectStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateObjectStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryChunkMetaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryChunkMetaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateChunkStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateChunkStatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterObjectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterObjectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryStorageAddressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryStorageAddressResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meta_service_proto_goTypes,
		DependencyIndexes: file_meta_service_proto_depIdxs,
		EnumInfos:         file_meta_service_proto_enumTypes,
		MessageInfos:      file_meta_service_proto_msgTypes,
	}.Build()
	File_meta_service_proto = out.File
	file_meta_service_proto_rawDesc = nil
	file_meta_service_proto_goTypes = nil
	file_meta_service_proto_depIdxs = nil
}
