// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: block_service.proto

package block_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueKey string `protobuf:"bytes,1,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"` // block entry's unique key
	Hash      string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`                            // hash of this block for data validation
	Binary    []byte `protobuf:"bytes,3,opt,name=binary,proto3" json:"binary,omitempty"`                        // the binary data of the block
}

func (x *BlockEntry) Reset() {
	*x = BlockEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockEntry) ProtoMessage() {}

func (x *BlockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_block_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockEntry.ProtoReflect.Descriptor instead.
func (*BlockEntry) Descriptor() ([]byte, []int) {
	return file_block_service_proto_rawDescGZIP(), []int{0}
}

func (x *BlockEntry) GetUniqueKey() string {
	if x != nil {
		return x.UniqueKey
	}
	return ""
}

func (x *BlockEntry) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BlockEntry) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

type FetchBlockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueKey  string `protobuf:"bytes,1,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"`
	FromMaster bool   `protobuf:"varint,2,opt,name=from_master,json=fromMaster,proto3" json:"from_master,omitempty"`
}

func (x *FetchBlockReq) Reset() {
	*x = FetchBlockReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchBlockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBlockReq) ProtoMessage() {}

func (x *FetchBlockReq) ProtoReflect() protoreflect.Message {
	mi := &file_block_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBlockReq.ProtoReflect.Descriptor instead.
func (*FetchBlockReq) Descriptor() ([]byte, []int) {
	return file_block_service_proto_rawDescGZIP(), []int{1}
}

func (x *FetchBlockReq) GetUniqueKey() string {
	if x != nil {
		return x.UniqueKey
	}
	return ""
}

func (x *FetchBlockReq) GetFromMaster() bool {
	if x != nil {
		return x.FromMaster
	}
	return false
}

type FetchBlockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *BlockEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *FetchBlockResp) Reset() {
	*x = FetchBlockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchBlockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchBlockResp) ProtoMessage() {}

func (x *FetchBlockResp) ProtoReflect() protoreflect.Message {
	mi := &file_block_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchBlockResp.ProtoReflect.Descriptor instead.
func (*FetchBlockResp) Descriptor() ([]byte, []int) {
	return file_block_service_proto_rawDescGZIP(), []int{2}
}

func (x *FetchBlockResp) GetEntry() *BlockEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// When the unique key here is the same, the file will be overwritten.
type StoreBlockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *BlockEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *StoreBlockReq) Reset() {
	*x = StoreBlockReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreBlockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBlockReq) ProtoMessage() {}

func (x *StoreBlockReq) ProtoReflect() protoreflect.Message {
	mi := &file_block_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBlockReq.ProtoReflect.Descriptor instead.
func (*StoreBlockReq) Descriptor() ([]byte, []int) {
	return file_block_service_proto_rawDescGZIP(), []int{3}
}

func (x *StoreBlockReq) GetEntry() *BlockEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type StoreBlockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StoreBlockResp) Reset() {
	*x = StoreBlockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreBlockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBlockResp) ProtoMessage() {}

func (x *StoreBlockResp) ProtoReflect() protoreflect.Message {
	mi := &file_block_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBlockResp.ProtoReflect.Descriptor instead.
func (*StoreBlockResp) Descriptor() ([]byte, []int) {
	return file_block_service_proto_rawDescGZIP(), []int{4}
}

type DeleteBlockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueKey string `protobuf:"bytes,1,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"`
}

func (x *DeleteBlockReq) Reset() {
	*x = DeleteBlockReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlockReq) ProtoMessage() {}

func (x *DeleteBlockReq) ProtoReflect() protoreflect.Message {
	mi := &file_block_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlockReq.ProtoReflect.Descriptor instead.
func (*DeleteBlockReq) Descriptor() ([]byte, []int) {
	return file_block_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBlockReq) GetUniqueKey() string {
	if x != nil {
		return x.UniqueKey
	}
	return ""
}

type DeleteBlockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBlockResp) Reset() {
	*x = DeleteBlockResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlockResp) ProtoMessage() {}

func (x *DeleteBlockResp) ProtoReflect() protoreflect.Message {
	mi := &file_block_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlockResp.ProtoReflect.Descriptor instead.
func (*DeleteBlockResp) Descriptor() ([]byte, []int) {
	return file_block_service_proto_rawDescGZIP(), []int{6}
}

// The block storage service needs to report the service health status to the
// meta information service for scheduling.
type HealthReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address      string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	StoreGroup   int64  `protobuf:"varint,2,opt,name=store_group,json=storeGroup,proto3" json:"store_group,omitempty"`
	StoreNode    int64  `protobuf:"varint,3,opt,name=store_node,json=storeNode,proto3" json:"store_node,omitempty"`
	Capacity     int64  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	CapacityUsed int64  `protobuf:"varint,5,opt,name=capacity_used,json=capacityUsed,proto3" json:"capacity_used,omitempty"`
	IsLeader     bool   `protobuf:"varint,6,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_block_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_block_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_block_service_proto_rawDescGZIP(), []int{7}
}

func (x *HealthReport) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HealthReport) GetStoreGroup() int64 {
	if x != nil {
		return x.StoreGroup
	}
	return 0
}

func (x *HealthReport) GetStoreNode() int64 {
	if x != nil {
		return x.StoreNode
	}
	return 0
}

func (x *HealthReport) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *HealthReport) GetCapacityUsed() int64 {
	if x != nil {
		return x.CapacityUsed
	}
	return 0
}

func (x *HealthReport) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

var File_block_service_proto protoreflect.FileDescriptor

var file_block_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x57, 0x0a, 0x0a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x4f, 0x0a,
	0x0d, 0x46, 0x65, 0x74, 0x63, 0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x1d,
	0x0a, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a,
	0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x41,
	0x0a, 0x0e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x2f, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x22, 0x40, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x71, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e,
	0x74, 0x72, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2f, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x22, 0xc6, 0x01, 0x0a, 0x0c, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x75, 0x73, 0x65,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74,
	0x79, 0x55, 0x73, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x32, 0xf8, 0x01, 0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x46, 0x65, 0x74, 0x63, 0x68, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x12, 0x1c, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a,
	0x1d, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x4b, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1c,
	0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4e, 0x0a,
	0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1d, 0x2e, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x11, 0x5a,
	0x0f, 0x2e, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_block_service_proto_rawDescOnce sync.Once
	file_block_service_proto_rawDescData = file_block_service_proto_rawDesc
)

func file_block_service_proto_rawDescGZIP() []byte {
	file_block_service_proto_rawDescOnce.Do(func() {
		file_block_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_block_service_proto_rawDescData)
	})
	return file_block_service_proto_rawDescData
}

var file_block_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_block_service_proto_goTypes = []interface{}{
	(*BlockEntry)(nil),      // 0: block_service.BlockEntry
	(*FetchBlockReq)(nil),   // 1: block_service.FetchBlockReq
	(*FetchBlockResp)(nil),  // 2: block_service.FetchBlockResp
	(*StoreBlockReq)(nil),   // 3: block_service.StoreBlockReq
	(*StoreBlockResp)(nil),  // 4: block_service.StoreBlockResp
	(*DeleteBlockReq)(nil),  // 5: block_service.DeleteBlockReq
	(*DeleteBlockResp)(nil), // 6: block_service.DeleteBlockResp
	(*HealthReport)(nil),    // 7: block_service.HealthReport
}
var file_block_service_proto_depIdxs = []int32{
	0, // 0: block_service.FetchBlockResp.entry:type_name -> block_service.BlockEntry
	0, // 1: block_service.StoreBlockReq.entry:type_name -> block_service.BlockEntry
	1, // 2: block_service.BlockService.FetchBlock:input_type -> block_service.FetchBlockReq
	3, // 3: block_service.BlockService.StoreBlock:input_type -> block_service.StoreBlockReq
	5, // 4: block_service.BlockService.DeleteBlock:input_type -> block_service.DeleteBlockReq
	2, // 5: block_service.BlockService.FetchBlock:output_type -> block_service.FetchBlockResp
	4, // 6: block_service.BlockService.StoreBlock:output_type -> block_service.StoreBlockResp
	6, // 7: block_service.BlockService.DeleteBlock:output_type -> block_service.DeleteBlockResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_block_service_proto_init() }
func file_block_service_proto_init() {
	if File_block_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_block_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchBlockReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchBlockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreBlockReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreBlockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlockReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlockResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_block_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_block_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_block_service_proto_goTypes,
		DependencyIndexes: file_block_service_proto_depIdxs,
		MessageInfos:      file_block_service_proto_msgTypes,
	}.Build()
	File_block_service_proto = out.File
	file_block_service_proto_rawDesc = nil
	file_block_service_proto_goTypes = nil
	file_block_service_proto_depIdxs = nil
}
